### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by tuttiq** [guiceolin/dotfiles#1]
pyhton install module core doesn't work (raises an excpetion).
after that initializing terminal shows an PATH error:
~/dotfiles/core/../modules_enabled/**/PATH: no such file or directory

**Comment by tuttiq** [comment]
It fixes the error message if after "python install module core" you run "python install module git" and "python install module rbenv".

**Comment by guiceolin** [comment]
well, fixed.
i removed all python code: no code, no bugs.
